Repository umrover/mrover-ros, pull requests merged in 2022-12, with the labels that each got.

#257 ISH GUI Integration
  CMakeLists.txt
  config/esw.yaml
  launch/basestation.launch
  msg/Carousel.msg
  msg/ScienceTemperatures.msg
  package.xml
  src/teleop/gui/src/components/Amino.vue
  src/teleop/gui/src/components/Cache.vue
  src/teleop/gui/src/components/Carousel.vue
  src/teleop/gui/src/components/Chlorophyll.vue
  src/teleop/gui/src/components/GenerateReport.vue
  src/teleop/gui/src/components/ISHTask.vue
  src/teleop/gui/src/components/Raman.vue
  src/teleop/gui/src/components/SelectSite.vue
  src/teleop/gui/src/components/Sudan.vue
  src/teleop/gui/src/components/ToggleButton.vue
Labels: teleoperation

#260 Add stuck box and interface for stuck box on auton GUI
  src/teleop/gui/src/components/AutonWaypointEditor.vue
Labels: teleoperation

#170 Add ability to control the robotic arm and other brushed motors
  CMakeLists.txt
  config/esw.yaml
  config/teleop.yaml
  launch/brushed.launch
  launch/jetson.launch
  src/esw/brushed_motors/Controller.cpp
  src/esw/brushed_motors/Controller.h
  src/esw/brushed_motors/ControllerMap.cpp
  src/esw/brushed_motors/ControllerMap.h
  src/esw/brushed_motors/I2C.cpp
  src/esw/brushed_motors/I2C.h
  src/esw/brushed_motors/ROSHandler.cpp
  src/esw/brushed_motors/ROSHandler.h
  src/esw/brushed_motors/Test.cpp
  src/esw/brushed_motors/Test.h
  src/esw/brushed_motors/main.cpp
  src/teleop/jetson/jetson_teleop.py
Labels: esw

#281 Fix issues with turning sensitivity on joystick
  config/teleop.yaml
Labels: teleoperation

#288 Don't publish invalid TFs
  src/esw/imu_driver.py
  src/localization/gps_linearization.py
Labels: localization
