Repository umrover/mrover-ros, pull requests merged in 2022-06, with the labels that each got.

#26 Class to represent SE3 poses
  package.xml
  src/util/SE3.py
  src/util/tf_utils.py
Labels: core

#32 Add clang format and python lint action
  .github/workflows/style.yml
  setup.py
  src/gazebo/differential_drive_6w.cpp
  src/gazebo/differential_drive_6w.hpp
  src/localization.py
  src/navigation/common.py
  src/navigation/navigation.py
  src/navigation/waypoint.py
  src/perception/aruco_detect.cpp
  src/perception/aruco_detect.hpp
  src/util/SE3.py
  src/util/tf_utils.py
Labels: devops

#44 Faster CI
  .github/workflows/catkin.yml
Labels: enhancement, core

#48 Use Riley's docker container for ultra fast CI
  .github/workflows/catkin.yml
Labels: enhancement, devops

#25 Perception publish tags as a world pose
  .clang-format
  CMakeLists.txt
  launch/nav.launch
  launch/percep.launch
  msg/MarkerInfo.msg
  src/gazebo/differential_drive_6w.cpp
  src/gazebo/differential_drive_6w.hpp
  src/perception/README.md
  src/perception/aruco_detect.cpp
  src/perception/aruco_detect.hpp
  src/perception/aruco_processing.cpp
  src/perception/filter.hpp
  src/perception/se3.cpp
  src/perception/se3.hpp
  src/perception/se3_conversion.cpp
Labels: perception, enhancement
