Repository umrover/mrover-ros, pull requests merged in 2022-09, with the labels that each got.

#91 New Python SE3 interface
  .gitignore
  CMakeLists.txt
  pyproject.toml
  src/navigation/context.py
  src/navigation/drive.py
  src/navigation/search.py
  src/navigation/waypoint.py
  src/util/SE2.py
  src/util/SE3.py
  src/util/SO3.py
  test/example/python_test.py
  test/navigation/drive.py
  test/util/SE3_test.py
  test/util/SE3_tf_test.py
  test/util/SE3_tf_test.test
  test/util/SO3_test.py
Labels: enhancement, refactor, core

#107 6 Wheel Drive Plugin Refactor
  .github/workflows/style.yml
  clang_check.sh
  src/gazebo/differential_drive_6w.cpp
  src/gazebo/differential_drive_6w.hpp
Labels: refactor, simulation, high pri

#130 Handles invalid values in point cloud properly
  src/perception/aruco_processing.cpp
Labels: perception, bug, sim-gap

#123 Add style checking script that also does python
  .dockerignore
  .github/workflows/catkin.yml
  .github/workflows/style.yml
  Dockerfile
  clang_check.sh
  package.xml
  requirements.txt
  src/navigation/context.py
  src/navigation/search.py
  src/util/SE3.py
  style.sh
Labels: devops

#100 Added Base Station GUI with 5 blank pages and Basic Drive and Arm Controls.
  .gitignore
  CMakeLists.txt
  config/teleop.yaml
  launch/teleop.launch
  msg/Chassis.msg
  package.xml
  src/teleop/gui/gui.sh
  src/teleop/gui/package.json
  src/teleop/gui/src/App.vue
  src/teleop/gui/src/app.js
  src/teleop/gui/src/assets/logo.png
  src/teleop/gui/src/components/ArmControls.vue
  src/teleop/gui/src/components/AutonTask.vue
  src/teleop/gui/src/components/Checkbox.vue
  src/teleop/gui/src/components/ControlGUI.vue
  src/teleop/gui/src/components/DriveControls.vue
  src/teleop/gui/src/components/ERDTask.vue
  src/teleop/gui/src/components/ESTask.vue
  src/teleop/gui/src/components/ISHTask.vue
  src/teleop/gui/src/components/Menu.vue
  src/teleop/gui/src/components/MenuButton.vue
  src/teleop/gui/src/components/SATask.vue
  src/teleop/gui/src/index.html
  src/teleop/gui/src/router/index.js
  src/teleop/gui/src/static/.gitkeep
  src/teleop/gui/src/static/arm.png
  src/teleop/gui/src/static/gate_location.png
  src/teleop/gui/src/static/gps_tangent_icon.png
  src/teleop/gui/src/static/help.png
  src/teleop/gui/src/static/joystick.png
  src/teleop/gui/src/static/location_marker_icon.png
  src/teleop/gui/src/static/logitech_joystick.png
  src/teleop/gui/src/static/map_marker.png
  src/teleop/gui/src/static/map_marker_highlighted.png
  src/teleop/gui/src/static/map_marker_projected.png
  src/teleop/gui/src/static/mrover.png
  src/teleop/gui/src/static/soil_ac.png
  src/teleop/gui/src/static/switching.png
  src/teleop/gui/src/static/tangent-2.png
  src/teleop/gui/src/static/xbox_controller.png
  src/teleop/gui/webpack.config.dev.js
  src/teleop/gui/yarn.lock
  src/teleop/jetson/jetson_teleop.py
Labels: teleoperation

#125 Add install script for repository
  .gitignore
  install.py
Labels: devops

#109 Visualizes state machine structure and highlights active state
  requirements.txt
  scripts/debug_course_publisher.py
  scripts/visualizer.py
  src/navigation/navigation.py
  style.sh
Labels: navigation, simulation, high pri

#131 Add Teleop Starter Project
  CMakeLists.txt
  starter_project/teleop/.gitignore
  starter_project/teleop/CMakeLists.txt
  starter_project/teleop/README.md
  starter_project/teleop/babel.config.js
  starter_project/teleop/gui_starter.sh
  starter_project/teleop/launch/teleop_starter.launch
  starter_project/teleop/package.json
  starter_project/teleop/src/App.vue
  starter_project/teleop/src/app.js
  starter_project/teleop/src/assets/logo.png
  starter_project/teleop/src/components/DriveControls.vue
  starter_project/teleop/src/components/Menu.vue
  starter_project/teleop/src/components/MenuButton.vue
  starter_project/teleop/src/index.html
  starter_project/teleop/src/router/index.js
  starter_project/teleop/src/static/mrover.png
  starter_project/teleop/webpack.config.dev.js
  starter_project/teleop/yarn.lock
Labels: teleoperation

#154 Changed wheel control interface back to [-1,1]
  config/teleop.yaml
  launch/teleop.launch
  src/teleop/gui/src/components/DriveControls.vue
  src/teleop/jetson/jetson_teleop.py
Labels: teleoperation, esw, high pri

#160 Remove GUI install from CMakeLists, add node and yarn to install script
  CMakeLists.txt
  install.py
Labels: teleoperation, devops

#89 Add rover drive code and networking config scripts
  .gitignore
  CMakeLists.txt
  config/esw.yaml
  config/teleop.yaml
  install.py
  launch/gui.launch
  launch/jetson.launch
  launch/teleop.launch
  msg/ODriveState.msg
  msg/WheelData.msg
  package.xml
  scripts/networking_setup_basestation
  scripts/networking_setup_jetson
  src/esw/drive/odrive_control.py
  src/teleop/gui/src/components/DriveControls.vue
  src/teleop/jetson/jetson_teleop.py
Labels: esw

#141 rostest Integration and Regression Testing
  .dockerignore
  .github/workflows/catkin.yml
  .github/workflows/style.yml
  .gitignore
  CMakeLists.txt
  Dockerfile
  install.py
  scripts/debug_course_publisher.py
  scripts/visualizer.py
  src/esw/drive/odrive_control.py
  src/navigation/context.py
  src/navigation/search.py
  src/navigation/waypoint.py
  src/teleop/jetson/jetson_teleop.py
  src/util/course_service.py
  style.sh
  test/integration/integration.py
  test/integration/integration.test
Labels: simulation, devops, high pri

#162 IMU + GPS drivers
  CMakeLists.txt
  config/esw.yaml
  launch/localization_test.launch
  msg/CalibrationStatus.msg
  package.xml
  requirements.txt
  src/esw/drive/odrive_control.py
  src/esw/imu_driver.py
  src/teleop/jetson/jetson_teleop.py
Labels: localization, esw

#175 Make odrive_control accept twist messages now
  config/esw.yaml
  install.py
  launch/jetson.launch
  src/driveController/driveController.py
  src/esw/drive/odrive_control.py
  test/integration/integration.py
Labels: esw

#176 created the enabled interface
  msg/EnableAuton.msg
  msg/GPSWaypoint.msg
Labels: navigation, teleoperation

#153 Add Raspberry Pi 4 Support & CMakeLists restructure
  CMakeLists.txt
  setup.py
Labels: esw, devops

#104 Gate traversal
  config/gazebo/env_description/post/meshes/4x4_1000-1.blend
  config/gazebo/env_description/post/meshes/4x4_1000-1.dae
  config/gazebo/env_description/post/meshes/4x4_1000-1.png
  config/gazebo/env_description/post/meshes/4x4_1000-1.svg
  config/gazebo/env_description/world.world
  scripts/debug_course_publisher.py
  src/navigation/context.py
  src/navigation/gate.py
  src/navigation/navigation.py
  src/navigation/search.py
  src/navigation/single_fiducial.py
  src/navigation/trajectory.py
  src/navigation/waypoint.py
  src/util/np_utils.py
Labels: navigation, enhancement
