Repository umrover/mrover-ros, pull requests merged in 2023-01, with the labels that each got.

#293 fix enable service
  scripts/debug_course_publisher.py
  scripts/debug_enable_auton.py
  src/navigation/context.py
  src/teleop/gui/src/components/AutonTask.vue
  src/util/course_publish_helpers.py
  src/util/course_service.py
  test/integration/integration.py
Labels: navigation, high pri

#291 Merge Camera GUI component into master
  src/teleop/gui/src/components/CameraInfo.vue
  src/teleop/gui/src/components/CameraSelection.vue
  src/teleop/gui/src/components/Cameras.vue
  src/teleop/gui/src/components/ISHTask.vue
Labels: teleoperation

#275 As/nav deactivation state
  scripts/debug_disable_auton.py
  src/navigation/context.py
  src/navigation/navigation.py
  src/navigation/state.py
Labels: navigation

#302 Fix Auton GUI for new auton enable service interface
  src/teleop/gui/src/components/AutonWaypointEditor.vue
Labels: teleoperation

#295 Misc: RViz path plotting, update script, remove camera feed
  config/rviz/basestation.rviz
  launch/auton.launch
  package.xml
  update.sh
Labels: devops

#303 Add ESLint and Prettier to GUI Code
  .gitignore
  src/teleop/gui/.eslintignore
  src/teleop/gui/.eslintrc.js
  src/teleop/gui/.prettierrc.json
  src/teleop/gui/package.json
  src/teleop/gui/webpack.config.dev.js
Labels: teleoperation

#301 Add Moteus and Joint State data tables
  CMakeLists.txt
  msg/MotorsStatus.msg
  src/teleop/gui/src/components/ControlGUI.vue
  src/teleop/gui/src/components/JointStateTable.vue
  src/teleop/gui/src/components/MoteusStateTable.vue
Labels: teleoperation

#311 Add service testing debug node
  scripts/debug_service.py
Labels: teleoperation, devops

#308 fix sim to stop rover after not recieving updates for 100 loops
  src/gazebo/differential_drive_6w.cpp
  src/gazebo/differential_drive_6w.hpp
  src/navigation/state.py
Labels: navigation

#309 Publish map to base_link transform
  config/drone.yaml
  launch/drone.launch
  src/drone/mavros_tf_publisher.py
Labels: localization, drone

#314 Pass Clang
  src/esw/brushed_motors/ROSHandler.h
  src/esw/brushed_motors/Test.h
  src/esw/brushed_motors/main.cpp
  src/perception/tag_detector.cpp
Labels: enhancement

#317 Add publishing of Auton LED color to Auton GUI
  CMakeLists.txt
  src/teleop/gui/src/components/AutonTask.vue
  srv/ChangeAutonLEDState.srv
Labels: teleoperation

#292 Add more data displays to Auton GUI
  src/teleop/gui/src/components/AutonTask.vue
  src/teleop/gui/src/components/AutonWaypointEditor.vue
  src/teleop/gui/src/components/JoystickValues.vue
  src/teleop/gui/src/components/VelocityCommand.vue
Labels: teleoperation

#326 Remove legacy ODrive code
  CMakeLists.txt
  config/esw.yaml
  launch/brushed.launch
  launch/brushless.launch
  launch/jetson.launch
  launch/pi.launch
  msg/ODriveState.msg
  package.xml
  requirements.txt
  src/esw/drive/odrive_control.py
Labels: esw

#321 add odom frame infrastructure
  .gitignore
  config/localization.yaml
  src/localization/gps_linearization.py
  src/util/SE3.py
  test/util/SE3_test.py
Labels: localization

#323 EDM/ES GUIs PR
  src/teleop/gui/src/components/ArmControls.vue
  src/teleop/gui/src/components/AutonWaypointEditor.vue
  src/teleop/gui/src/components/CameraSelection.vue
  src/teleop/gui/src/components/Cameras.vue
  src/teleop/gui/src/components/DriveControls.vue
  src/teleop/gui/src/components/DriveVelDataH.vue
  src/teleop/gui/src/components/DriveVelDataV.vue
  src/teleop/gui/src/components/ERDRoverMap.vue
  src/teleop/gui/src/components/ERDTask.vue
  src/teleop/gui/src/components/ERDWaypointEditor.vue
  src/teleop/gui/src/components/ERDWaypointItem.vue
  src/teleop/gui/src/components/ESTask.vue
  src/teleop/gui/src/components/JointStateTable.vue
  src/teleop/gui/src/components/Menu.vue
  src/teleop/gui/src/components/MoteusStateTable.vue
  src/teleop/gui/src/components/OdometryReading.vue
  src/teleop/gui/src/components/PDBFuse.vue
  src/teleop/gui/src/router/index.js
  src/teleop/gui/src/store/index.js
  src/teleop/gui/src/store/modules/erd.js
  src/teleop/gui/src/store/modules/map.js
Labels: teleoperation
