Repository umrover/mrover-ros, pull requests merged in 2023-10, with the labels that each got.

#591 Improve CMake. Automatically find message and service files. Add many utility macros.
  CMakeLists.txt
Labels: devops, 2024

#594 Small fixes to perception
  src/perception/zed_wrapper/zed_wrapper.bridge.cu
  src/perception/zed_wrapper/zed_wrapper.cpp
  src/perception/zed_wrapper/zed_wrapper.hpp
Labels: refactor

#559 State library
  config/navigation.yaml
  msg/StateMachineStateUpdate.msg
  msg/StateMachineStructure.msg
  msg/StateMachineTransition.msg
  setup.py
  src/navigation/approach_post.py
  src/navigation/context.py
  src/navigation/drive.py
  src/navigation/failure_identification/__init__.py
  src/navigation/failure_identification/failure_identification.py
  src/navigation/failure_identification/watchdog.py
  src/navigation/navigation.py
  src/navigation/post_backup.py
  src/navigation/recovery.py
  src/navigation/search.py
  src/navigation/state.py
  src/navigation/waypoint.py
  src/util/state_lib/__init__.py
  src/util/state_lib/state.py
  src/util/state_lib/state_machine.py
  src/util/state_lib/state_publisher_server.py
  test/util/state_lib/simple_test.py
  test/util/state_lib/test_external_data.py
  test/util/state_lib/test_loop_overrun.py
Labels: navigation, 2024, auton
