Repository umrover/mrover-ros, pull requests merged in 2023-03, with the labels that each got.

#335 Add ISH GUI and Science Node
  CMakeLists.txt
  config/esw.yaml
  config/teleop.yaml
  launch/basestation.launch
  launch/cameras.launch
  launch/jetson.launch
  msg/Carousel.msg
  msg/Diagnostic.msg
  msg/HeaterData.msg
  msg/ScienceTemperature.msg
  msg/Spectral.msg
  scripts/debug_service.py
  src/esw/brushed_motors/ROSHandler.cpp
  src/esw/brushed_motors/ROSHandler.h
  src/esw/brushless.py
  src/esw/science.py
  src/teleop/gui/src/components/Amino.vue
  src/teleop/gui/src/components/AutonWaypointEditor.vue
  src/teleop/gui/src/components/Cache.vue
  src/teleop/gui/src/components/Carousel.vue
  src/teleop/gui/src/components/Chlorophyll.vue
  src/teleop/gui/src/components/GenerateReport.vue
  src/teleop/gui/src/components/ISHTask.vue
  src/teleop/gui/src/components/JointStateTable.vue
  src/teleop/gui/src/components/LEDIndicator.vue
  src/teleop/gui/src/components/OpenLoopControl.vue
  src/teleop/gui/src/components/Raman.vue
  src/teleop/gui/src/components/SAArmControls.vue
  src/teleop/gui/src/components/SelectSite.vue
  src/teleop/gui/src/components/Sudan.vue
  src/teleop/gui/src/components/ToggleButton.vue
  srv/ChangeDeviceState.srv
  srv/ChangeHeaterState.srv
  srv/ChangeServoAngle.srv
Labels: teleoperation, esw

#330 Add Joint locking options and servoing vs open loop controls to arm controls GUI Component
  CMakeLists.txt
  msg/JointLock.msg
  src/teleop/gui/src/components/ArmControls.vue
  src/teleop/gui/src/components/Checkbox.vue
  src/teleop/jetson/jetson_teleop.py
Labels: teleoperation

#209 githook for grabbing large files from google drive
  .githooks/post-checkout
Labels: devops

#372 Control what perception publishes tag to
  CMakeLists.txt
  config/DetectorParams.cfg
  config/gazebo/env_description/ground.dae
  config/gazebo/env_description/world.world
  config/rviz/auton_sim.rviz
  launch/auton.launch
  src/gazebo/gazebo_ros_openni_kinect.cpp
  src/perception/README.md
  src/perception/filter.hpp
  src/perception/tag_detector.cpp
  src/perception/tag_detector.hpp
  src/perception/tag_detector.processing.cpp
Labels: perception

#371 added projected points and estimated gate points icon
  CMakeLists.txt
  msg/GPSPointList.msg
  msg/GPSWaypoint.msg
  msg/NavMetadata.msg
  src/teleop/gui/src/components/AutonRoverMap.vue
Labels: teleoperation

#377 Global EKF
  config/ekf.yaml
  config/gazebo/env_description/world.world
  config/localization.yaml
  config/rviz/auton_sim.rviz
  config/sim_ekf.yaml
  launch/auton.launch
  launch/auton_sim.launch
  launch/simulator.launch
  rover_description/rover_gazebo_plugins.xacro
  scripts/test_ekf.py
  src/esw/imu_driver.py
  src/gazebo/differential_drive_6w.cpp
  src/gazebo/differential_drive_6w.hpp
  src/localization/gps_linearization.py
  src/localization/imu_packager.py
  src/localization/passthrough_filter.py
  src/localization/sim_imu_driver.py
  src/util/np_utils.py
  test/integration/integration.test
Labels: localization

#395 Fix Rover Icon Bearing on GUI Maps
  src/teleop/gui/src/components/ArmControls.vue
  src/teleop/gui/src/components/AutonRoverMap.vue
  src/teleop/gui/src/components/AutonTask.vue
  src/teleop/gui/src/components/AutonWaypointEditor.vue
  src/teleop/gui/src/components/Cache.vue
  src/teleop/gui/src/components/Carousel.vue
  src/teleop/gui/src/components/Checkbox.vue
  src/teleop/gui/src/components/ERDTask.vue
  src/teleop/gui/src/components/SATask.vue
  src/teleop/gui/src/utils.js
Labels: teleoperation

#398 Bash script to copy the moveit arm subpackage to and from the main catkin workspace directory.
  scripts/copy_arm_pkg.sh
  src/teleop/mrover_arm/.setup_assistant
  src/teleop/mrover_arm/config/gazebo_mrover_arm.urdf
Labels: teleoperation

#402 adjust auton gui format
  src/teleop/gui/src/components/AutonWaypointEditor.vue
  src/teleop/gui/src/components/IMUCalibration.vue
  src/teleop/gui/src/components/JoystickValues.vue
  src/teleop/gui/src/components/VelocityCommand.vue
Labels: teleoperation

#407 Make CI pull pip requirements
  .github/workflows/catkin.yml
  .github/workflows/style.yml
Labels: devops

#362 Monitor network bandwidth
  CMakeLists.txt
  config/esw.yaml
  launch/basestation.launch
  msg/NetworkBandwidth.msg
  src/esw/brushless.py
  src/esw/network_monitor.py
Labels: esw

#374 Created a Comm Readout component
  src/teleop/gui/src/components/AutonTask.vue
  src/teleop/gui/src/components/AutonWaypointEditor.vue
  src/teleop/gui/src/components/CommReadout.vue
  src/teleop/gui/src/components/ControlGUI.vue
  src/teleop/gui/src/components/ERDTask.vue
  src/teleop/gui/src/components/ISHTask.vue
  src/teleop/gui/src/components/JoystickValues.vue
  src/teleop/gui/src/components/ROSDebug.vue
  src/teleop/gui/src/components/ROSEcho.vue
  src/teleop/gui/src/components/ROSService.vue
  src/teleop/gui/src/components/SATask.vue
Labels: teleoperation
