Repository umrover/mrover-ros, pull requests merged in 2024-02, with the labels that each got.

#638 Make the simulator publish an image for the stereo camera
  src/simulator/simulator.gui.cpp
  src/simulator/simulator.hpp
  src/simulator/simulator.params.cpp
  src/simulator/simulator.physics.cpp
  src/simulator/simulator.render.cpp
  src/simulator/simulator.sensors.cpp
  src/simulator/urdf.cpp
  src/simulator/wgpu_objects.hpp
Labels: simulation, 2024

#637 Bno085 driver
  src/esw/fw/imu/bno055_serial.ino
  src/esw/fw/imu/bno085_serial.ino
  src/esw/imu_driver.py
Labels: localization, 2024

#620 GPU-accelerated obstacle detection
  .gitattributes
  CMakeLists.txt
  config/ObjectDetectorParams.cfg
  config/simulator/simulator.yaml
  data/yolov8n_mallet_bottle_better.onnx
  launch/perception.launch
  launch/zed.launch
  launch/zed_test.launch
  msg/DetectedObject.msg
  msg/DetectedObjectType.msg
  msg/LongRangeTag.msg
  msg/LongRangeTags.msg
  package.xml
  plugins/object_detector_plugin.xml
  src/perception/image_capture/image_capturepy.py
  src/perception/object_detector/inference.cu
  src/perception/object_detector/inference.cuh
  src/perception/object_detector/inference_wrapper.cu
  src/perception/object_detector/inference_wrapper.hpp
  src/perception/object_detector/logger.cu
  src/perception/object_detector/logger.cuh
  src/perception/object_detector/main.cpp
  src/perception/object_detector/object_detector.cpp
  src/perception/object_detector/object_detector.hpp
  src/perception/object_detector/object_detector.processing.cpp
  src/perception/object_detector/pch.hpp
  src/util/loop_profiler.hpp
Labels: perception, 2024

#647 Gui cameras
  src/teleoperation/backend/consumers.py
  src/teleoperation/frontend/src/components/AutonTask.vue
  src/teleoperation/frontend/src/components/AutonWaypointEditor.vue
  src/teleoperation/frontend/src/components/CameraFeed.vue
  src/teleoperation/frontend/src/components/CameraInfo.vue
  src/teleoperation/frontend/src/components/CameraSelection.vue
  src/teleoperation/frontend/src/components/Cameras.vue
  src/teleoperation/frontend/src/components/ISHTask.vue
  src/teleoperation/frontend/src/components/SATask.vue
Labels: teleoperation

#656 Localization in integration test
  .github/workflows/ci.yml
  pyproject.toml
  test/integration/integration.py
Labels: sim-gap

#653 Simulator camera lock for cinematic shots
  .gitmodules
  Dockerfile
  src/simulator/model.cpp
  src/simulator/pch.hpp
  src/simulator/simulator.controls.cpp
  src/simulator/simulator.gui.cpp
  src/simulator/simulator.hpp
  src/simulator/simulator.render.cpp
Labels: simulation

#652 Costmap touchup
  src/perception/cost_map/cost_map.cpp
  src/perception/cost_map/cost_map.hpp
  src/perception/cost_map/cost_map.processing.cpp
  src/perception/cost_map/pch.hpp
Labels: perception
